In [8]:
import numpy as np 
n_array=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

'int32'

In [3]:
n_array.ndim

2

In [4]:
n_array.shape

(3, 4)

In [5]:
n_array.size

12

In [7]:
n_array.dtype.name

'int32'

In [10]:
a=np.array([11,12,13,14])
b=np.array([1,2,3,4])
c=a-b
c

array([10, 10, 10, 10])

In [11]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [12]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
b<2

array([ True, False, False, False])

In [15]:
A1=np.array([[1,1],[0,1]])
A2=np.array([[2,0],[3,4]])
A1*A2



array([[2, 0],
       [0, 4]])

In [16]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

In [17]:
n_array[0,1]

1

In [18]:
n_array[0,0:3]

array([0, 1, 2])

In [19]:
n_array[:,1]

array([1, 5, 9])

In [20]:
n_array[0,:]

array([0, 1, 2, 3])

In [21]:
n_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
n_array.shape=(6,2)
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
n_array.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [25]:
import pandas as pd
pd.Series(np.random.randn(5))

0    0.347453
1    0.634283
2    0.515212
3    0.780682
4    2.217635
dtype: float64

In [26]:
pd.Series(np.random.randn(5),index=['a','b','c','d','e'])

a   -0.032743
b   -1.483004
c   -3.000432
d   -0.389197
e    1.507003
dtype: float64

In [27]:
d={'A':10,'B':20,'C':30}
pd.Series(d)

A    10
B    20
C    30
dtype: int64

In [29]:
d={'c1':pd.Series(['A','B','C']),'c2':pd.Series([1,2.,3.,4.])}
df=pd.DataFrame(d)
df

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

In [32]:
d={'c1':['A','B','C','D'],'c2':[1,2.0,3.0,4.0]}
df=pd.DataFrame(d)
print(df)

  c1   c2
0  A  1.0
1  B  2.0
2  C  3.0
3  D  4.0


In [46]:
print('This is how to read and write DATA')

This is how to read and write DATA


In [45]:
print('This is how to read CSV')
#d=pd.read_csv('Data/Student_Weight_Status_Category_Reporting_Results_Begining_2010.csv')
#d[0:5]['AREA NAME']
print('This is how to write CSV')
#d={'c1':pd.Series(['A','B','C']),'c2':pd.Series([1,2.,3.,4.])}
#df=pd.DataFrame(d)
#df.to_csv('sample_data.csv')

This is how to read CSV
This is how to write CSV


In [47]:
print('This is how to read XLS')
#d=pd.read_excel('Data/Student_Weight_Status_Category.xls')
print('This is how to write XLS')
#df.to_excel('sample_data.xls')

This is how to read XLS
This is how to write XLS


In [48]:
print('This is how to read JSON')
#import json
#json_data=open('Data/Student_Weights_Status_Category.json')
#data=json.load(json_data)
#json_data.close()
#pd.read_json()

This is how to read JSON


In [49]:
print('This is how to read Database')
#pd.read_sql_table(table_name, con)
#table_name: This refers to the name of the SQL table in a database
#con: This refers to the SQLAlchemy engine
#pd.read_sql_query(sql, con)
#sql: This refers to the SQL query that is to be executed
#con: This refers to the SQLAlchemy engine

This is how to read Database


In [51]:
print('Checking the missing data')
#d['Location 1'].isnull()
#d['Location 1'].isnull().value_counts()
#d['Location 1'].dropna()
#d=d.dropna(how='any')

Checking the missing data


In [55]:
print('Filling the missing data')
df = pd.DataFrame(np.random.randn(5, 3), index=['a0', 'a10','a20', 'a30', 'a40'],columns=['X', 'Y', 'Z'])
df

Filling the missing data


X         Y         Z
a0  -0.490730 -1.379123 -0.449804
a10  0.355931 -1.479990 -1.179176
a20 -0.134560 -1.204804 -0.211657
a30  0.412147 -0.299045  1.449004
a40  0.548224  0.086035 -0.593517

In [58]:
df = df.reindex(['a0', 'a1', 'a10', 'a11', 'a20', 'a21','a30', 'a31', 'a40', 'a41'])
df

X         Y         Z
a0  -0.490730 -1.379123 -0.449804
a1        NaN       NaN       NaN
a10  0.355931 -1.479990 -1.179176
a11       NaN       NaN       NaN
a20 -0.134560 -1.204804 -0.211657
a21       NaN       NaN       NaN
a30  0.412147 -0.299045  1.449004
a31       NaN       NaN       NaN
a40  0.548224  0.086035 -0.593517
a41       NaN       NaN       NaN

In [59]:
df.fillna(0)

X         Y         Z
a0  -0.490730 -1.379123 -0.449804
a1   0.000000  0.000000  0.000000
a10  0.355931 -1.479990 -1.179176
a11  0.000000  0.000000  0.000000
a20 -0.134560 -1.204804 -0.211657
a21  0.000000  0.000000  0.000000
a30  0.412147 -0.299045  1.449004
a31  0.000000  0.000000  0.000000
a40  0.548224  0.086035 -0.593517
a41  0.000000  0.000000  0.000000

In [61]:
df.fillna(method='pad')#filling with forward propagation

X         Y         Z
a0  -0.490730 -1.379123 -0.449804
a1  -0.490730 -1.379123 -0.449804
a10  0.355931 -1.479990 -1.179176
a11  0.355931 -1.479990 -1.179176
a20 -0.134560 -1.204804 -0.211657
a21 -0.134560 -1.204804 -0.211657
a30  0.412147 -0.299045  1.449004
a31  0.412147 -0.299045  1.449004
a40  0.548224  0.086035 -0.593517
a41  0.548224  0.086035 -0.593517

In [65]:
df.fillna(df.mean()) #moyenne

X         Y         Z
a0  -0.490730 -1.379123 -0.449804
a1   0.138203 -0.855386 -0.197030
a10  0.355931 -1.479990 -1.179176
a11  0.138203 -0.855386 -0.197030
a20 -0.134560 -1.204804 -0.211657
a21  0.138203 -0.855386 -0.197030
a30  0.412147 -0.299045  1.449004
a31  0.138203 -0.855386 -0.197030
a40  0.548224  0.086035 -0.593517
a41  0.138203 -0.855386 -0.197030

In [66]:
print('String Operation')
#df = pd.read_csv('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')
#df['AREA NAME'][0:5]
#df['AREA NAME'][0:5].str.extract('(\w+)')
#df['AREA NAME'][0:5].str.extract('(\w+)\s(\w+)')
#df[df['GRADE LEVEL'] == 'ELEMENTARY']
#df['AREA NAME'][0:5].str.upper()
#df['AREA NAME'][0:5].str.lower()
#df['AREA NAME'][0:5].str.len()
#df['AREA NAME'][0:5].str.split(' ')
#df['AREA NAME'][0:5].str.replace('DISTRICT$', 'DIST')

String Operation


In [67]:
print('Merging data')
#d[['AREA NAME', 'COUNTY']][0:5]
#p1 = d[['AREA NAME', 'COUNTY']][0:2]
#p2 = d[['AREA NAME', 'COUNTY']][2:5]
#pd.concat([p1,p2])
#concatenated = pd.concat([p1,p2], keys = ['p1','p2'])#adding key
#concatenated
#concatenated.ix['p1']

Merging data


In [68]:
print('Aggregation operations')
#average number of students :data = d[d['GRADE LEVEL'] == 'ELEMENTARY']
#data['NO. OBESE'].mean() : moyenne of students who are obese
#data['NO. OBESE'].sum() :sum of students who are obese
#data['NO. OBESE'].max() :max of students who are obese
#data['NO. OBESE'].min() :min of students who are obese
#data['NO. OBESE'].std() :standard deviation number of obese students
#data = df[(d['GRADE LEVEL'] == 'ELEMENTARY') &(d['COUNTY'] == 'DELAWARE')]
#data['COUNTY'].count() :count the total number of schools with the ELEMENTARY grade inthe DELAWARE county

Aggregation operations


In [69]:
print('Data operation :JOINS')
#grade_lookup = {'GRADE LEVEL': pd.Series(['ELEMENTARY','MIDDLE/HIGH', 'MISC']),'LEVEL': pd.Series([1, 2, 3])}
#grade_lookup = DataFrame(grade_lookup)
#df[['GRADE LEVEL']][0:5]

Data operation :JOINS


In [70]:
print('Data operation :The inner join')
#d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='inner')
#d_sub[['GRADE LEVEL', 'LEVEL']]

Data operation :The inner join


In [71]:
print('Data operation :The left outer join')
#d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='left')
#d_sub[['GRADE LEVEL', 'LEVEL']]

Data operation :The left outer join


In [72]:
print('Data operation :The full outer join')
#d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='outer')
#d_sub[['GRADE LEVEL', 'LEVEL']]

Data operation :The full outer join


In [ ]:
print('Data operation :The groupby function')
#df['NO. OBESE'].groupby(d['GRADE LEVEL']).sum()
#d['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate(sum)
#df['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate([sum, mean,std])